version: 0.2

phases:
    install:
        runtime-versions:
          nodejs: 14
        commands:
          - echo "installing nodejs 14"
    pre_build:
        commands:
          - echo "we are in the pre build phase"
    build:
        commands:
          - echo "we are in the build block"
          - echo "we will run some tests"
          - grep -Fq "app.use(express.json())" index.js
    post_build:
        commands:
          - echo "we are in the post build phase"